name: Maven CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove Elm cache
      run: |
        echo "🧹 Removing corrupted Elm cache..."
        rm -rf ~/.elm
        rm -rf elm-stuff

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install


